spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ecommerce
    password: ecommerce1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

logging:
  level:
    kr.go.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
